function MyMex(filename)
addpath(genpath(pwd));
if(nargin == 0)
	filename = 'TestStieBrockett';
end
mex('-R2018a', '-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/.vs/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/.vs/ROPTLIB/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/.vs/ROPTLIB/v15/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/.vs/ROPTLIB/v15/ipch/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/.vs/ROPTLIB/v15/ipch/AutoPCH/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/.vs/ROPTLIB/v15/ipch/AutoPCH/164433e706b84785/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/.vs/ROPTLIB/v15/ipch/AutoPCH/4fa875e8ac0192bd/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/BinaryFiles/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/BinaryFiles/x64/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/BinaryFiles/x64/Debug/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/BinaryFiles/x64/Debug/ROPTLIB.tlog/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/IRPG/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/IRPG/SPCA/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/IRPG/SVPCA/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/IRPG/SVPCA/PenCPG/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/IRPG/TextureInpainting/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/CFRQBlindDecon2D/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/CSFRQPhaseRetrieval/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/EucQuadratic/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/FRankE3FMatCom/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/FRankE3FMatCom/DownloadLMaFit/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/FRankE3FMatCom/DownloadLMaFit/LMaFit-adp/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/FRankE3FMatCom/DownloadLMaFit/LMaFit-adp/Utilities/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/LRTRSR1tCGvsLRTRSR1/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/LinearEigVal/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/SPDKarcherMean/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/LRTRSR1/StieSoftICA/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForCpp/SPCA/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Matlab/ForMatlab/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/SparseBLAS/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/fftw/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/wavelet/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/project.xcworkspace/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/project.xcworkspace/xcshareddata/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/configuration/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/project.xcworkspace/xcuserdata/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/project.xcworkspace/xcuserdata/whuang.xcuserdatad/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/xcshareddata/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/xcshareddata/xcschemes/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/xcuserdata/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/xcuserdata/whuang.xcuserdatad/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/xcuserdata/whuang.xcuserdatad/xcdebugger/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/ROPTLIB_mac.xcodeproj/xcuserdata/whuang.xcuserdatad/xcschemes/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/cwrapper/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/cwrapper/blas/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/cwrapper/lapack/', ...
'-I/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/test/', ...
['./test/' filename '.cpp'], ...
'/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/CFixedRankQ2F.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/CStiefel.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/CSymFixedRankQ.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/Element.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/Euclidean.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/FixedRankE.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/FixedRankE3F.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/FixedRankQ2F.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/Grassmann.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/Manifold.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/MultiManifolds.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/PoincareBall.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/SPDManifold.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/SmartSpace.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/Sphere.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/SphereTx.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/Stiefel.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Manifolds/SymFixedRankQ.cpp', ...
'/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/BlasLapackCppWrapper.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/ForDebug.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/MinPNormConHull.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/SparseMatrix.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/Spline.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/Timer.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/randgen.cpp', ...
'/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/SparseBLAS/nist_spblas.cpp', ...
'/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Others/wavelet/wavelet.cpp', ...
'/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/CFRankQ2FBlindDecon2D.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/CSFRQPhaseRetrieval.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/CStieBrockett.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/EucQuadratic.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/FRankE3FMatCompletion.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/FRankESparseApprox.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/FRankETextureInpainting.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/FRankEWeightApprox.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/FRankQ2FMatCompletion.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/GrassMatCompletion.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/GrassPCA.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/GrassRQ.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/GrassSVPCA.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/ObliqueSPCA.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/PoincareEmbeddings.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/Problem.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/ProdStieSumBrockett.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/SFRQLyapunov.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/SPDKarcherMean.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/SphereConvexHull.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/SphereSparsestVector.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/SphereTxRQ.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/StieBrockett.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/StieSPCA.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/StieSoftICA.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/juliaProblem.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Problems/mexProblem.cpp', ...
'/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/IARPG.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/IRPG.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/LRBFGS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/LRBFGSSub.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/LRBroydenFamily.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/LRTRSR1.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/LRTRSR1woR.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RADAM.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RADAMSP.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RAMSGRAD.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RAMSGRADSP.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RBFGS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RBFGSSub.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RBroydenFamily.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RCG.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RGS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RNewton.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RSD.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RSGD.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RSVRG.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RTRNewton.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RTRSD.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RTRSR1.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/RWRBFGS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SVRLRBFGS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SVRLRBroydenFamily.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/Solvers.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversNSM.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversNSMPGLS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversNSMSub.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversNSMSubLS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversSM.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversSMLS.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversSMSVRG.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversSMSto.cpp', '/home/ubuntu/Documents/Sync/Codes/newROPTLIB/ROPTLIB/Solvers/SolversSMTR.cpp', ...
['-D' upper(filename)], '-DROPTLIB_WITH_FFTW', '-lfftw3', '-lmwblas', '-lmwlapack', '-output', ['./BinaryFiles/' filename ]);
end